# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - binary: mongodb_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: netbsd
        goarch: arm64
    flags:
      - -v
      - -a
      - -tags=netgo
    ldflags: |
        -X github.com/percona/mongodb_exporter/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/percona/mongodb_exporter/vendor/github.com/prometheus/common/version.Revision={{.FullCommit}}
        -X github.com/percona/mongodb_exporter/vendor/github.com/prometheus/common/version.Branch={{.Tag}}
        -X github.com/percona/mongodb_exporter/vendor/github.com/prometheus/common/version.BuildUser={{.Env.USER}}@{{.Tag}}
        -X github.com/percona/mongodb_exporter/vendor/github.com/prometheus/common/version.BuildDate={{time "20060102-15:04:05"}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
