# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    #- make check-vendor-synced
builds:
  - binary: mongodb_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: netbsd
        goarch: arm64
    flags:
      - -v
      - -a
      - -tags=netgo
    ldflags: |
        -X {{.Env.GO_PACKAGE}}/vendor/github.com/prometheus/common/version.Version={{.Env.APP_VERSION}}
        -X {{.Env.GO_PACKAGE}}/vendor/github.com/prometheus/common/version.Revision={{.Env.APP_REVISION}}
        -X {{.Env.GO_PACKAGE}}/vendor/github.com/prometheus/common/version.Branch={{.Env.TRAVIS_BRANCH}}
        -X {{.Env.GO_PACKAGE}}/vendor/github.com/prometheus/common/version.BuildUser={{.Env.USER}}@{{.Env.TRAVIS_APP_HOST}}
        -X {{.Env.GO_PACKAGE}}/vendor/github.com/prometheus/common/version.BuildDate={{.Env.BUILD_TIME}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    netbsd: NetBSD
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Env.APP_VERSION }}_checksums.txt'
snapshot:
  name_template: "{{ .ShortCommit }}"
changelog:
  skip: true
release:
  github:
    owner: percona
    name: mongodb_exporter
  draft: true
  prerelease: auto
